CREATE TABLE IF NOT EXISTS arsip_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  judul_arsip VARCHAR(255) NOT NULL,
  kategori VARCHAR(100) NOT NULL DEFAULT 'Lainnya',
  deskripsi TEXT NULL,
  nama_file VARCHAR(255) NOT NULL,
  nama_asli VARCHAR(255) NOT NULL,
  tipe_file VARCHAR(100) NOT NULL,
  ukuran_file BIGINT NOT NULL DEFAULT 0,
  file_url VARCHAR(255) NOT NULL,
  file_year INT NULL,
  record_count INT DEFAULT 0,
  parsed_data TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
